vpc_cidr                        = "10.0.0.0/16"
vpc-name                        = "cali-vpc"
igw-name                        = "cali-igw"
pub_cidr_block                  = ["10.0.1.0/24", "10.0.50.0/24"]
private_cidr_block              = ["10.0.100.0/24", "10.0.150.0/24"]
eks_cluster_name                = "cali-EKS-cluster"
eks_cluster_iam_role_name       = "cali-eks-iam-role"
sg_name                         = "cali-eks-sg"
node_group_name                 = "cali-node-group"
node_role_name                  = "cali-node-role"
fargate_profile_name            = "cali-fargate-profile"
namespace                       = "fargate-node"
fargate_pod_execution_role_name = "cali-fargate-profile-pod-execution-role"
